# Development
---
version: "3"

services:
  database:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: "knowledge"
      POSTGRES_USER: "knowledge"
      POSTGRES_PASSWORD: "secret"
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      - knowledge

  api:
    image: "knowledge-api:dev"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - gems:/knowledge/vendor
      - .:/knowledge

    ports:
      - 3000:3000
    depends_on:
      - database
    networks:
      - knowledge

volumes:
  gems:
  database:

networks:
  knowledge:
